collections:
  logs:
    output: true

# permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "logs"
    values:
      layout: "log"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: https://images.unsplash.com/photo-1571008887538-b36bb32f4571?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=81
      image-credit: Sporlab/Unsplash
      image-credit-link: https://unsplash.com/photos/XiZ7pRvCzro
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Settings for SEO
title: "pr.markgrindy.com"
tagline: "Personal record"
description: "Project reports, training logs, and other entries."
url: "https://pr.markgrindy.com" # the base hostname & protocol for your site
favicon: /favicon.png
logo: /assets/img/pr-markgrindy-logo-white.svg

# Settings for Related Posts
related:
  minCommonTags: 1 # default 2 (min number of tags articles must have in common to be displayed)
  maxRelated: 3 # default = 3 (max number of related articles to display)
  maxTags: 3 # default = 3 (max number of tags in common to display on page)

# author:
twitter:
  username: markgrindy
  card: summary
# facebook:
#   facebook:app_id - a Facebook app ID for Facebook insights
#   facebook:publisher - a Facebook page URL or ID of the publishing entity
#   facebook:admins - a Facebook user ID for domain insights linked to a personal account
# logo: /assets/logo.png
# social:
#   name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter
# google_site_verification: 123456789 # for verifying ownership via Google webmaster tools
lang: en_US

sheets:
  postsData: "2PACX-1vSCR28RzPNncW_hexILbVFrIMJPJeShUw3YZdJYTBcuAqDKC2Nrt6bZ9zYEFJzL7G05g18LKm67aOi3"
