collections:
  authors:
    output: true

# permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      author: mark
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

title: "swatchword.com"
tagline: "/swäCHˌwərd/ noun: a sample expression of a core belief."
description: "Project reports, training logs, and other entries."
url: "https://swatchword.com" # the base hostname & protocol for your site

# Settings for Related Posts
related:
  minCommonTags: 1 # default 2 (min number of tags articles must have in common to be displayed)
  maxRelated: 3 # default = 3 (max number of related articles to display)
  maxTags: 3 # default = 3 (max number of tags in common to display on page)

# author:
twitter:
  username: markgrindy
  card: summary
# facebook:
#   facebook:app_id - a Facebook app ID for Facebook insights
#   facebook:publisher - a Facebook page URL or ID of the publishing entity
#   facebook:admins - a Facebook user ID for domain insights linked to a personal account
# logo: /assets/logo.png
# social:
#   name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter
# google_site_verification: 123456789 # for verifying ownership via Google webmaster tools
lang: en_US
